# Default values for ps-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: percona/percona-server-mysql-operator
  tag: 0.11.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# rbac: settings for deployer RBAC creation
rbac:
  # rbac.create: if false RBAC resources should be in place
  create: true

# serviceAccount: settings for Service Accounts used by the deployer
serviceAccount:
  # serviceAccount.create: Whether to create the Service Accounts or not
  create: true

env:
  logStructured: false
  logLevel: "INFO"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

disableTelemetry: false

backup:
  enabled: true
  image: perconalab/percona-server-mysql-operator:main-backup
  #    schedule:
  #      - name: "sat-night-backup"
  #        schedule: "0 0 * * 6"
  #        keep: 3
  #        storageName: s3-us-west
  #      - name: "daily-backup"
  #        schedule: "0 0 * * *"
  #        keep: 5
  #        storageName: s3
  #    backoffLimit: 6
  imagePullPolicy: Always
  #    initImage: perconalab/percona-server-mysql-operator:main
  #    containerSecurityContext:
  #      privileged: true
  storages:
    #      azure-blob:
    #        type: azure
    #        azure:
    #          container: CONTAINER-NAME
    #          prefix: PREFIX-NAME
    #          endpointUrl: https://accountName.blob.core.windows.net
    #          credentialsSecret: SECRET-NAME
    s3-us-west:
      type: s3
      verifyTLS: true
      #        nodeSelector:
      #          storage: tape
      #          backupWorker: 'True'
      #        resources:
      #          requests:
      #            memory: 1G
      #            cpu: 600m
      #        affinity:
      #          nodeAffinity:
      #            requiredDuringSchedulingIgnoredDuringExecution:
      #              nodeSelectorTerms:
      #              - matchExpressions:
      #                - key: backupWorker
      #                  operator: In
      #                  values:
      #                  - 'True'
      #        topologySpreadConstraints:
      #        - labelSelector:
      #            matchLabels:
      #              app.kubernetes.io/name: percona-server
      #          maxSkew: 1
      #          topologyKey: kubernetes.io/hostname
      #          whenUnsatisfiable: DoNotSchedule
      #        tolerations:
      #          - key: "backupWorker"
      #            operator: "Equal"
      #            value: "True"
      #            effect: "NoSchedule"
      #        annotations:
      #          testName: scheduled-backup
      #        labels:
      #          backupWorker: 'True'
      #        schedulerName: 'default-scheduler'
      #        priorityClassName: 'high-priority'
      #        containerSecurityContext:
      #          privileged: true
      #        podSecurityContext:
      #          fsGroup: 1001
      #          supplementalGroups: [1001, 1002, 1003]
      s3:
        bucket: S3-BACKUP-BUCKET-NAME-HERE
        credentialsSecret: cluster1-s3-credentials
        region: us-west-2
#          prefix: ""
