annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - '**Update note 1**: `.Values.vmselect.statefulSet.updateStrategy` was changed to `.Values.vmselect.statefulSet.spec.updateStrategy`'
    - '**Update node 2**: `.Values.vmselect.podManagementPolicy` was changed to `.Values.vmselect.statefulSet.spec.podManagementPolicy`'
    - '**Update note 3**: `.Values.vmselect.deployment.strategy` was changed to `.Values.vmselect.deployment.spec.strategy`'
    - '**Update note 4**: `.Values.vmselect.statefulSet.enabled` was replaced by `.Values.vmselect.mode`, which accepts `deployment`, `statefulSet` values'
    - bump version of VM components to [v1.112.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.112.0)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-cluster
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/cluster-victoriametrics
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog
apiVersion: v2
appVersion: v1.112.0
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
description: Victoria Metrics Cluster version - high-performance, cost-effective and
  scalable TSDB, long-term remote storage for Prometheus
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmcluster
- vmselect
- vminsert
- vmstorage
- tsdb
- monitoring
- kubernetes
- observability
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-cluster
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.18.0
